### ISSUE TITLE
Enable Solid FA Icons

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#1]
### Website Issue Report

https://community.rockrms.com

**Description of Issue**

Would it be possible to enable "Solid" fonts (as an alternative, not the default) on the Community theme so that we can do things like `fas fa-sitemap` when creating recipes that point out icons in the Rock UI? It looks like "Light" is the default on that theme, and you can't override it with a solid.

**Comment by jonedmiston** [comment]
Added.
