### ISSUE TITLE
Individual donation page CVV field size

### ISSUE THREAD

**Issue by luke-infoministry** [SparkDevNetwork/RockWebsites#10]
### Website Issue Report

**URL:** https://www.rockrms.com/donate/individual [after money amount entered, 'Next' is clicked (cc entry form)]
**Description of Issue**
The CVV field is formatted in such a way that only one digit of the 3/4 digit code displays at a time. When entering "345", 3 is visible, then 4, then 5.  clicking away will show '3' again, but not the 3 digit string.

**Comment by garrettjohnson** [comment]
Fixed. Thanks @luke-infoministry
