### ISSUE TITLE
RockU Videos Checkmarks not showing

### ISSUE THREAD

**Issue by cjfountain** [SparkDevNetwork/RockWebsites#100]
### Website Issue Report

**URL:** 
https://community.rockrms.com/rocku/communication/sms-pipeline
https://community.rockrms.com/rocku/communication/system-emails
https://community.rockrms.com/rocku/content-channels/content-library
https://community.rockrms.com/rocku/individuals-in-rock/data-integrity
https://community.rockrms.com/rocku/individuals-in-rock/assessments-conflict-profile
https://community.rockrms.com/rocku/individuals-in-rock/assessments-spiritual-gifts

**Description of Issue**

These videos are not getting checked off after I watch them.

**Comment by nairdo** [comment]
We updated that RockU page's Lava with the newer [AppendWatches](https://community.rockrms.com/lava/filters/other-filters#appendwatches) Lava command replacing the older technique which was trying to fetch that data via SQL.  We also worked with Cecillia to confirm that her recent 'watched' checkmarks are showing up now.
