### ISSUE TITLE
Not Indication of Accepted Answers on Q&A

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#11]
### Website Issue Report

https://community.rockrms.com/ask/using/2212 (example)

**Description of Issue**

The new site seems to have no visual indication of the "accepted" answer. The old site turned the accepted answer green, but the new one has no indication (that I can see.) At the URL above, the sole answer has been accepted, but you can't determine that by looking at it.

**Comment by garrettjohnson** [comment]
Fixed, we now include a green border an accepted answer text.

![image](https://user-images.githubusercontent.com/374209/57339539-e186af00-70e6-11e9-8452-f9fda8b2e2a9.png)
