### ISSUE TITLE
Download File link generating bad URL

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/RockWebsites#12]
### Website Issue Report

**URL:** https://community.rockrms.com/recipes/33/advanced-dynamic-data-block-use

**Description of Issue**

![image](https://user-images.githubusercontent.com/19762670/57318130-37dff780-70bf-11e9-9d9f-6780dafc9170.png)

When I visit this article and scroll down to the Download File button, the button sends you to this link.

https://community.rockrms.com/recipes/33/Liquid%20error:%20Object%20reference%20not%20set%20to%20an%20instance%20of%20an%20object.

**Comment by cabal95** [comment]
Also seems to do it on any recipe that has a downloadable file as I was able to reproduce on another recipe as well. So it isn't something with just that recipe.

**Comment by garrettjohnson** [comment]
Fixed, the page was showing links when there were no attached files. Thanks @NuclearTacos !
