### ISSUE TITLE
Previous version notification on manual pages obscures breadcrumbs

### ISSUE THREAD

**Issue by luke-infoministry** [SparkDevNetwork/RockWebsites#13]
### Website Issue Report

https://community.rockrms.com/documentation/book/5/60/content
**Description of Issue**

When the manual for a previous version of Rock is selected, the yellow "Note: a newer version of this book is available..." notification at the top of the page overlaps and obscures the breadcrumbs for the page.

Breadcrumbs (in white) obscured by the yellow notification:

![Breadcrumbs obscured - Brave_2019-05-08_21-40-35](https://user-images.githubusercontent.com/32314302/57431586-1f1f3100-71e8-11e9-8129-17e7c303fd70.png)

Breadcrumbs highlighted to show overlap/collision

![Breadcrumbs highlighted - Brave_2019-05-08_21-40-35](https://user-images.githubusercontent.com/32314302/57431597-247c7b80-71e8-11e9-8808-aec69c7c7932.png)

It seems like the page content isn't being "pushed down" by the notification the way I would expect.

This happens on all manual pages that I tested.

**Comment by garrettjohnson** [comment]
Fixed. Notification now appears below the orange header. Thanks!
