### ISSUE TITLE
Lava Filter for PersonActionIdentifer shows wrong Rock version

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/RockWebsites#14]
### Website Issue Report

**URL:** https://community.rockrms.com/lava/filters/person-filters#personactionidentifier

**Description of Issue**
In looking at the required Rock Version, I think this should be Rock 8.7. 

The confusion here is when you update to Rock 8.7, there is a banner that says you should update your unsubscribe settings to use this filter.

**Comment by nairdo** [comment]
Thanks for spotting that. Yes, that should be v8.7 ([proof](https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.8.7/Rock/Lava/RockFilters.cs#L3221)).

I updated this in the Lava Docs.
