### ISSUE TITLE
"Your Votes" Not Available On Mobile Causes Viewing Issues

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#15]
### Website Issue Report

https://community.rockrms.com/ideas

**Description of Issue**

I'm seeing an issue that I can't reproduce 100%, but happens often enough that it's not a fluke.

First, note that there is no "Your Votes" button when viewing on mobile (like there is on desktop) on the /ideas page.

1. If I go to /ideas with a desktop browser and click "Your Votes" it filters to my votes as expected.

2. Often (but not always), if I THEN go to /ideas with a mobile device (logged in as the same user, of course), it too is filtered to "Your Votes" but since there is no Your Votes _button_ on mobile you're stuck in that mode and can't disable it.

3. Going back to /ideas on desktop and un-doing Your Votes then lets you see all ideas again on mobile.

**Comment by garrettjohnson** [comment]
Fixed to display toggle button on mobile
