### ISSUE TITLE
Can't Reply To Replies On Ideas Page

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#16]
### Website Issue Report

https://community.rockrms.com/ideas

I'm unable to reply to a comment unless it's my own comment. 

1. I go to https://community.rockrms.com/ideas/226/automatically-inactivate-a-group-member-when-archived

2. I made a comment that starts with _This sounds like a bug..._ and someone replied to it.

3. If I click the `...` menu on _her_  comment, I get no menu (thus can't reply), but if I click the `...` menu on MY comment, I get a menu where I have the option to reply.

![image](https://user-images.githubusercontent.com/3903408/57889106-96148500-77f9-11e9-9d33-2a70c0c03bd2.png)

This happens in both Chrome and Firefox on Win10 for me.

**Comment by JimMichael** [comment]
Maybe this issue is that you can't reply to replies?

**Comment by garrettjohnson** [comment]
Currently we're only allowing one level of commenting, fixed to hide the button when no options are available.
