### ISSUE TITLE
FB External Auth issues

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/RockWebsites#18]
### Website Issue Report

**URL:** https://community.rockrms.com/login?returnurl=/page/1247

**Description of Issue**

![image (2)](https://user-images.githubusercontent.com/19762670/58026122-673d2e00-7adb-11e9-9b43-d418baf566f1.png)

When you try to use FB login on community.rockrms.com, you get this message.

When you try to use FB login on Rocket Chat, it just goes to a blank screen.

**Comment by garrettjohnson** [comment]
Fixed
