### ISSUE TITLE
Profile name not updating with new First Name

### ISSUE THREAD

**Issue by nmphx** [SparkDevNetwork/RockWebsites#19]
### Website Issue Report

**URL:** _URL of the page_
https://community.rockrms.com/profile/d0ddeffc-8fbc-4237-a1ad-dda3d520dd6c/settings/profile

**Description of Issue**
Profile name not updating with new First Name

_please provide as much detail as possible_
Originally set up profile with Facebook login.  Needed to update the First Name. Profile first name field is updated, but Full Name header on Profile page is not updated accordingly.
![Slide1](https://user-images.githubusercontent.com/51347074/58843056-be87e600-8625-11e9-90fa-9e2ab20c6411.JPG)

**Comment by garrettjohnson** [comment]
Fixed, the name now properly updates. Thanks for your help!
