### ISSUE TITLE
Documentation Suggestion Gone

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#2]
### Website Issue Report

https://community.rockrms.com/documentation/book/1/145/content (as an example, but this affects all documentation pages)

**Description of Issue**

The ability to report a problem or make a suggestion within the documentation seems to have been lost in the move to the new site. Mentioning in case that wasn't intentional, and because I'm starting to see people enter documentation suggestions as /ideas

**Comment by jonedmiston** [comment]
Yep, working on bring that back. Should be ready soon.

**Comment by garrettjohnson** [comment]
Fixed, Thanks @JimMichael !
![image](https://user-images.githubusercontent.com/374209/56390441-e25fab80-61e0-11e9-8c7b-7e5694cf4a58.png)
