### ISSUE TITLE
Can't Vote On Mobile

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#22]
### Website Issue Report

https://community.rockrms.com/Ideas

When viewing the /ideas page on mobile, you cannot vote because the pop-up is blown off the right side of the screeen.
![file-8](https://user-images.githubusercontent.com/3903408/59945939-af2ed800-942e-11e9-8bc2-d698110b60a9.jpeg)
Turning the phone to landscape lets it partially appear, but that's not a great solution.

**Comment by garrettjohnson** [comment]
Fixed, the vote popover now displays below the vote button.
