### ISSUE TITLE
Hall of Fame Badge Shows on Every Profile

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#27]
### Website Issue Report

https://community.rockrms.com/profile/[ANY PROFILE GUID]

**Description of Issue**

It looks like the "Hall of Fame" badge is appearing on every profile on the site. I noticed it on someone in my org, then tested random people and everyone has the badge. I assume that's not intended :-D

**Comment by jonedmiston** [comment]
Can you confirm this? I'm not able to reproduce.

![image](https://user-images.githubusercontent.com/548178/61175994-7685a880-a56d-11e9-86f7-5a97354e6a9e.png)

**Comment by JimMichael** [comment]
This is what I see on every person I pick via Q&A... but ONLY when I'm logged in.
![image](https://user-images.githubusercontent.com/3903408/61176830-4e0da680-a58d-11e9-84be-3d3fe9b19a7d.png)

Maybe it's a caching issue, since I actually have the badge?

**Comment by JimMichael** [comment]
And just another data point... I just noticed that when I'm NOT logged in, when I view my own profile I don't see the Hall of Fame badge, either.

**Comment by jonedmiston** [comment]
Ah ok thanks. This badge appears to be using the current person and not the profile person. Thanks!

**Comment by garrettjohnson** [comment]
Fixed
