### ISSUE TITLE
Q&A Accepted Answers Badge Shows All Answers

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#29]
### Website Issue Report

https://community.rockrms.com/profile/[ProfileGuid]

**Description of Issue**

The _Q&A Accepted Answers_ badge seems to be showing _all_ questions I've answered vs. the "accepted" ones. Maybe that's Working As Designed but the label implies it's showing only accepted answers.
![image](https://user-images.githubusercontent.com/3903408/61176788-cc1d7d80-a58c-11e9-865f-1f9501137a29.png)

**Comment by garrettjohnson** [comment]
Fixed
