### ISSUE TITLE
Preview RX2018 Videos link 404's (for me)

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/RockWebsites#3]
### Website Issue Report

**URL:** https://www.rockrms.com/subscriptions

**Description of Issue**

I'm logged in as Chris Rea:
Clicking the "Preview RX2018 Videos" takes me to https://www.rockrms.com/page/1200, tells me it's a 404.
![image](https://user-images.githubusercontent.com/19762670/56458882-a5ff8d00-6351-11e9-99cf-1dabaf4f9d0c.png)

**Comment by garrettjohnson** [comment]
Fixed! Thanks Chris!
