### ISSUE TITLE
404s on What's New RockU Videos

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#30]
### Website Issue Report

https://community.rockrms.com/rocku

**Description of Issue**
The three featured video links at the top all generate a 404. Accessing them from within the New Videos button works fine. They seem to be using a bad /rockubeta route.

![image](https://user-images.githubusercontent.com/3903408/61178892-13236700-a5bd-11e9-8361-e557468bf670.png)

**Comment by garrettjohnson** [comment]
Fixed
