### ISSUE TITLE
UI Issue on Naming Conventions table

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/RockWebsites#31]
### Website Issue Report

**URL:** https://community.rockrms.com/Rock/BookContent/16#namingconventions

**Description of Issue**
Table is so wide, it goes on top of the menu on the right. Maybe setting zindex on the table, so it goes behind the menu would be good enough.

**Comment by garrettjohnson** [comment]
Fixed, made the table responsive. Thanks!
