### ISSUE TITLE
Can’t Click On Github Links in Rocket.Chat Mobile

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#34]
### Website Issue Report

This is really picky and not a website issue per-se, but it’s still highly annoying :-)

On the automatic feed from Github to Rocket.Chat, when using the RC _mobile_ client (iOS in my case), the issues posted in #github have links that are not clickable. 

The issues appear to be inside of some “collapsible panels” so clicking _anywhere_ within the issue (via the RC mobile client) does nothing more than collapse/expand the panel. This makes it really hard to quickly get to an issue from the mobile client, for people like me that monitor for new issues constantly.

**Comment by garrettjohnson** [comment]
@JimMichael  Are you able to open links at all inside iOS? 

The windows client currently has a bug that's preventing any links from opening. https://github.com/RocketChat/Rocket.Chat.Electron/issues/1100

**Comment by garrettjohnson** [comment]
Created issue with Rocket Chat https://github.com/RocketChat/Rocket.Chat.iOS/issues/2747

**Comment by JimMichael** [comment]
This fixed itself at some point with an updated Rocket.Chat client, so I'm closing.
