### ISSUE TITLE
Release Note Counters Sizing Issue

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/RockWebsites#37]
### Website Issue Report

**URL:** https://community.rockrms.com/releasenotes

**Description of Issue**
If you look at this page on an iPad, the counters at the top of the page are not padded correctly.

**Comment by garrettjohnson** [comment]
Fixed on tablet and mobile devices. Thank you

![www rockrms com_releasenotes(iPad)](https://user-images.githubusercontent.com/374209/63202605-51d69200-c03f-11e9-9a50-49f113f03bbc.png)
