### ISSUE TITLE
Search on Recipes Broken

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#38]
### Website Issue Report

https://community.rockrms.com/recipes

**Description of Issue**

When you search for a keyword on the Recipe page, you get results, but THOSE links are broken. 

1. Go to https://community.rockrms.com/recipes
2. Search for shortcode
3. Click any result link
4. Observe the error
![image](https://user-images.githubusercontent.com/3903408/63281577-9e55e380-c272-11e9-8124-e137b805228d.png)
It appears to be referencing links about /Ideas instead of /Recipes

**Comment by RileyGspark** [comment]
It looks like whoever (probably me) configured the results list mistakenly included "/ideas/" instead of "/recipes/" in the URL slug.
