### ISSUE TITLE
Documentation says Organization attributes instead of global attributes

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/RockWebsites#39]
### Website Issue Report

https://community.rockrms.com/documentation/bookcontent/8/153#emailgoogleapps

It says under broken images to go to Admin Tools > General Settings > Organization Attributes > Public Application Root.

Should say Admin Tools > General Settings > **Global** Attributes > Public Application Root.

**Comment by jonedmiston** [comment]
Done, thanks for the catch!
