### ISSUE TITLE
Sunscriptions Session Titles Are Too Large

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#4]
### Website Issue Report

https://community.rockrms.com/subscriptions/rx2018 (or other years)

**Description of Issue**

The H2 on the session titles just seems overly large, to my eyes. They dominate everything on the page and many wrap on even a wide viewport. 

![image](https://user-images.githubusercontent.com/3903408/56693530-4b946280-66aa-11e9-86a4-a43cb278ba85.png)

**Comment by garrettjohnson** [comment]
Downsized text to h3
