### ISSUE TITLE
Issues with the Rx2019 Schedule page

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/RockWebsites#40]
### Website Issue Report

**URL:** https://www.rockrms.com/rx2019/schedule

**Description of Issue**

_please provide as much detail as possible_
![image](https://user-images.githubusercontent.com/19762670/64823560-567a6180-d57d-11e9-8882-02a81f4527f6.png)

**Comment by garrettjohnson** [comment]
Fixed. Thanks!
