### ISSUE TITLE
EN - Vote Button on Ideas page needs to be updated

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/RockWebsites#41]
### Website Issue Report
**URL:** https://community.rockrms.com/Ideas

**Description of Issue**
Looking at this button, it looks like it is inactive. Maybe if this was bolder or somehow popped more, it would look like you should click the button. Perhaps, make it the Orange color if you can vote and the current color if you are out of votes.

![image](https://user-images.githubusercontent.com/7517351/65908162-7ab2ac80-e38b-11e9-9009-3491a1be5d79.png)

**Comment by garrettjohnson** [comment]
Updated. Thanks!
