### ISSUE TITLE
Documentation graphic has wrong number next to Header Content

### ISSUE THREAD

**Issue by tehtrav** [SparkDevNetwork/RockWebsites#42]
### Website Issue Report

**URL:** https://community.rockrms.com/documentation/bookcontent/14/161

**Description of Issue**

The last text item (Header Content) in the figure box labeled **ADD PAGE - ADVANCED SETTINGS** has a 5, when it should be a 6

<img width="819" alt="Screen Shot 2019-10-01 at 4 28 42 PM" src="https://user-images.githubusercontent.com/351975/65998136-bbccbe80-e468-11e9-8cec-ca6a68cb419f.png">

**Comment by garrettjohnson** [comment]
Fixed. Thank you!
