### ISSUE TITLE
2019 Takeaways Missing on Profile

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#43]
### Website Issue Report
https://community.rockrms.com/profile/b5c3c4e2-700e-4b78-add0-dd42fca7c276

**Description of Issue**

When logged into your profile page there is a Takeaways panel in right sidebar that only has buttons for 2017 and 2018

![image](https://user-images.githubusercontent.com/3903408/66176121-35f47300-e622-11e9-905d-8262a8bfaa10.png)

**Comment by garrettjohnson** [comment]
Fixed
