### ISSUE TITLE
Alpha Testers "Detailed List of Steps" link 404's

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/RockWebsites#44]
### Website Issue Report

**URL:** _https://www.rockrms.com/page/472_

**This page 404's when clicked**

To replicate:

- Go to the [Alpha/Beta Testers page](https://www.rockrms.com/get-involved/role/alpha-beta-testers) and read the _Alpha Testers_ section
- Select the [detailed list of steps link](https://www.rockrms.com/page/472)

![image](https://user-images.githubusercontent.com/8688424/66406559-6f760700-e9b1-11e9-92fc-6d082cca7826.png)

**Comment by garrettjohnson** [comment]
Fixed
