### ISSUE TITLE
Link Previews (in Rocket Chat) from Recipes have unresolved Lava

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/RockWebsites#49]
### Website Issue Report

**URL:** https://community.rockrms.com/recipes//23/creating-a-clean-customized-finance-weekly-report

**Description of Issue**

![image](https://user-images.githubusercontent.com/19762670/66774652-af445f00-ee87-11e9-9b4d-0f445ad7b476.png)

![image](https://user-images.githubusercontent.com/19762670/66774699-da2eb300-ee87-11e9-94d5-49b7bbaa5abf.png)

**Comment by garrettjohnson** [comment]
Fixed. Thank you
