### ISSUE TITLE
Roadmap Link in Footer Points to Trello

### ISSUE THREAD

**Issue by taylorbrooks** [SparkDevNetwork/RockWebsites#50]
### Website Issue Report

**URL:** rockrms.com

**Description of Issue**
![image](https://user-images.githubusercontent.com/117657/67588651-37462680-f71c-11e9-8158-156153cfc048.png)

**Comment by cabal95** [comment]
The Promo Shop link goes to Trello? ;) (couldn't resist)

**Comment by taylorbrooks** [comment]
I was 5 degrees off. 

Before I posted, I was like, "eh close enough". 😂

**Comment by garrettjohnson** [comment]
Fixed
