### ISSUE TITLE
Vote Count on Searched-For Ideas is Wrong

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#53]
### Website Issue Report

https://community.rockrms.com/Ideas

**Description of Issue**

If you search for an idea, the "Vote Count" on the resulting ideas is incorrect and doesn't reflect the actual vote count.

Example: Search for **sendgrid** and you will get one result that shows the idea has 22 votes, but if you click on (or go find) the idea it (at the time of this writing) has 61 votes.

Maybe this is just an issue of the search results being really outdated?

**Comment by garrettjohnson** [comment]
Fixed to display the correct count.
