### ISSUE TITLE
Community Site: Recipe Search Includes Unpublished Drafts

### ISSUE THREAD

**Issue by MichaelAllen** [SparkDevNetwork/RockWebsites#54]
### Website Issue Report

**URL:** https://community.rockrms.com/recipes/

**Description of Issue**

When performing a search, it is possible to access unpublished draft recipes from the search results.

**Reproduction Steps**
1. Visit the recipe page and search for "Personalized Prayer Requests"
1. Open the [top search result](https://community.rockrms.com/recipes/72)
1. See that the recipe is not actually complete, and shows "Draft" in the top right (see photo)

<img src="https://user-images.githubusercontent.com/282879/72211370-1af29400-3498-11ea-9120-40bf36c1fc1a.png">

**Comment by garrettjohnson** [comment]
Fixed. Thanks Michael!
