### ISSUE TITLE
Stale "Portal" page

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#55]
### Website Issue Report

https://www.rockrms.com/portal

**Description of Issue**

This page (using the old theme) appears to be outdated an inaccurate (the service represented doesn't exist and clicking "Order" buttons go to nonexistent site), and even though it doesn't seem to be linked-to anywhere from the new rockrms.com site, it's still findable via a google search... for example, it's the top hit when searching for "rockrms turnkey"

Should probably just be removed altogether, or maybe a put a redirect on it to https://www.rockrms.com/getstarted/hosting

**Comment by garrettjohnson** [comment]
Updated.
