### ISSUE TITLE
Poorly Formatted Text on Commitments Page

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#56]
### Website Issue Report

Don't think I can give a direct link because it's the "Commitments" page when you're viewing your own Organization (https://community.rockrms.com/organizations/[GUID]/commitments)

**Description of Issue**

Next to the _Giving Frequency_ there is a paragraph that is formatted poorly (no space between any of the sentences).

There is also a grammar issue in the last sentence, which reads: _Knowing this allow us to plan and allocate and resources better._

**Comment by JimMichael** [comment]
Just noticed the first sentence has a small issue, too: _This help us determine how often you will be giving_

**Comment by garrettjohnson** [comment]
Updated and fixed typos.
