### ISSUE TITLE
Lava Documentation for PersonActionIdentifier Update

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/RockWebsites#57]
### Website Issue Report

**URL:** https://community.rockrms.com/lava/filters/person-filters#personactionidentifier

**Description of Issue**
The documentation states that the `PersonActionIdentifier` should only be used for the _Photo Opt Out_ block. *However*, as of v8.7 & it's release notes it _should_ be used for Unsubscribe functionality. This means that it's at least compatible with some other components in Rock (but I don't know what to name them)

**Comment by garrettjohnson** [comment]
Updated with current blocks capable of using the PersonActionIdentifier.
