### ISSUE TITLE
v8.7+ Non-HTML Content migration to PersonActionIdentifier

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/RockWebsites#58]
### Website Issue Report

**URL:** https://www.rockrms.com/technicalreleasenotes

**Description of Issue**
When upgrading a system to 8.7, the _*Technical*_ release notes (but not release notes) state that:
```We've updated the way the 'unsubscribe' functionality works. Be sure to look at the generic Unsubscribe HTML in the Email medium (under Admin Tools > Communications > Communication Mediums) and make similar changes to any custom templates you have (replacing Unsubscribe/{{ Person.UrlEncodedKey }} with Unsubscribe/{{ Person | PersonActionIdentifier:'Unsubscribe' }}).```

However, what is not clear is that the Communication Medium's "Non-HTML Content" should also be updated.

A better way to state this would be:
```We've updated the way the 'unsubscribe' functionality works. Be sure to look at the generic Unsubscribe HTML in the Email medium (under Admin Tools > Communications > Communication Mediums) and make similar changes to any custom templates you have (replacing Unsubscribe/{{ Person.UrlEncodedKey }} with Unsubscribe/{{ Person | PersonActionIdentifier:'Unsubscribe' }}). You will also need to update the Non-HTML Content for the Email Communication Medium (replacing &p={{ Person.UrlEncodedKey }} with &p={{ Person | PersonActionIdentifier:'Unsubscribe' }} )```

**However**, I'm unsure how to communicate this properly as:

1. I do not believe most people who read the release notes read the technical release notes iunfortunately)
2. There will be a 'breaking change' (if that's the right term) if organizations _have not_ updated before v11 as the v8.6 default will be changed/deprecated (this may be a misunderstanding on my part).... https://github.com/SparkDevNetwork/Rock/commit/8cb3869fa7f8a234f9855fd8b3549832558cb95e

This is related to #57

**Comment by JimMichael** [comment]
I agree it's confusing, but will note that the Technical Release Notes are what is displayed on screen when you're about to upgrade. I would _think_ most people read those yellow boxes, but I agree it could be "publicized" better in the main release notes, too.

**Comment by garrettjohnson** [comment]
Updated the release notes.
