### ISSUE TITLE
"Ministry Impact" footer link incorrect

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/RockWebsites#63]
### Website Issue Report

**URL:** _https://community.rockrms.com/_

**Description of Issue**

The _Ministry Impact_ link in the footer of the page points to /Documentation instead of whatever it is supposed to
<img width="622" alt="Monosnap 2020-04-22 14-57-51" src="https://user-images.githubusercontent.com/8688424/80027959-06b42f00-84aa-11ea-8d25-8df7b8556636.png">

**Comment by garrettjohnson** [comment]
Fixed link. Thank you!
