### ISSUE TITLE
404 error using search on RockRMS

### ISSUE THREAD

**Issue by MCoulterFBCN** [SparkDevNetwork/RockWebsites#65]
### Website Issue Report

**URL:** Community.rockrms.com

**Description of Issue**

Example: If you use the search box on the Manuals page to search for more than one word, it works fine.  But on the Search results page, if you type more than one word in the search box you will get a 404 page.  This seems to be the same experience on the other pages that use the search box.

**Comment by garrettjohnson** [comment]
Fixed on all community site search boxes. Thank you
