### ISSUE TITLE
Ideas with Backslash In Title Cause 404

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#66]
### Website Issue Report

https://community.rockrms.com/Ideas

**Description of Issue**

Someone added an Idea with a `\` in the title, and clicking, on it causes a 404. 
![image](https://user-images.githubusercontent.com/3903408/82131529-ae680880-979b-11ea-8177-c1dd95982416.png)

**Comment by garrettjohnson** [comment]
Fixed
