### ISSUE TITLE
Version History Sponsorship icon positioning

### ISSUE THREAD

**Issue by andypullen** [SparkDevNetwork/RockWebsites#67]
### Website Issue Report

**URL:** https://www.rockrms.com/versionhistory

**Description of Issue**
The positioning of the sponsorship badges is broken on WebKit browsers (Safari for Mac and iOS). 

<img width="1022" alt="rock-sponsorship-issue" src="https://user-images.githubusercontent.com/9940032/82906009-77bb8c00-9f19-11ea-83ee-39e71aad5f89.png">

**Comment by garrettjohnson** [comment]
Fixed. Thank you!

**Comment by andypullen** [comment]
The absolute positioning on `.fa-gem` is now causing the icon to be positioned wrong, fyi. It looks like the issue is a little deeper, between `.sponsor`, `.fa-gem`, and `.text-wrap-margin` all needing a different layout (flex or floats maybe).

**Comment by garrettjohnson** [comment]
@andypullen Can you post a screenshot? I don't have a Mac to test on right now, just an iPad.

**Comment by andypullen** [comment]
Yep! The issue is the same on my iPad, if that helps. Firefox and Chrome-based browsers position it all fine.
![Screen Shot 2020-05-26 at 2 28 39 PM](https://user-images.githubusercontent.com/9940032/82952195-609e8d80-9f5d-11ea-8383-84d21369b647.png)

**Comment by garrettjohnson** [comment]
Looks like the latest version of iOS introduced the bug. Added a workaround, thank you again!
