### ISSUE TITLE
Invalid example Lava in Lava Docs

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/RockWebsites#68]
### Website Issue Report

**URL:** https://community.rockrms.com/lava/commands/entity-commands#count

**Description of Issue**

The example given:

```
{% attendance where:'DidAttend == true && GroupId == 56' count:'true' %}
  {{ count }}            
{% endattendance %}
```

is no longer valid in Rock v9 because of the new AttendanceOccurrence table. `GroupId` is not a column in the database anymore.

**Comment by garrettjohnson** [comment]
Updated to use Content Channel Items instead. Thanks!
