### ISSUE TITLE
RockU

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/RockWebsites#69]
### Website Issue Report

**URL:** 
https://community.rockrms.com/rocku/core-concepts

**Description of Issue**
When logged in to RockU, I am unable to see which videos I completed/watched.  For example, yesterday I watched a set of videos from Core Concepts on my phone.  It showed each of the videos with a √ [check mark] as I completed the video (except for the videos that are only 1 minute long... it would show I completed those - Separate issue).

I logged in today to pick up where I left off, but the RockU site no longer has check marks for the videos I watched.

I am thinking the check mark should stay/show when I am logged in, correct?

Two Potential Issues:

1. RockU would not capture (with a check mark) the completion of a video that is around 1 min in lenght.
2. RockU did not keep my video completions (with a check mark) the day after I completed them.

_please provide as much detail as possible_

**Comment by garrettjohnson** [comment]
We're working on the issue now.

**Comment by garrettjohnson** [comment]
Rock U video view information has been re-enabled. Thank you
