### ISSUE TITLE
Viewing Ideas Causes Exception

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#7]
### Website Issue Report

https://community.rockrms.com/Ideas

**Description of Issue**

Clicking on any idea link to show the details throws an exception.

**Comment by JimMichael** [comment]
This only seems to happen when logged in. When logged out they show as expected.

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in https://github.com/SparkDevNetwork/Rock-SparkSite/commit/cfd49effd3f58bc33c85e3aa08db98b91da182d9

**Comment by ethan-sparkdevnetwork** [comment]
Copied the updated block to the website.
