### ISSUE TITLE
Issue logging in with www.rockrms.com URLs

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/RockWebsites#71]
### Website Issue Report

https://www.rockrms.com/page/1267

**Description of Issue**

When visiting the Recipe page with www.rockrms.com instead of community.rockrms.com, I am not logged in.  Even if I clear cookies and then login, I am not logged in when I visit https://www.rockrms.com/page/1267, but I am when I visit https://comunity.rockrms.com/page/1267

**Comment by garrettjohnson** [comment]
We should have this issue solved on the RockRMS.com properties. If you're still seeing problems shoot me a message on Rocket.Chat and I'll investigate what's going on with your auth cookies.
