### ISSUE TITLE
Misspelling on Podcast 102 page.

### ISSUE THREAD

**Issue by darringraham** [SparkDevNetwork/RockWebsites#72]
### Website Issue Report

**URL:** _URL of the page_
https://community.rockrms.com/connect/podcast-episode-102-rock-mobile

**Description of Issue**
Fishook is misspelled at the bottom of the page.

"We are thankful for Rock Partner, Fishhok."

**Comment by sparkdevnetwork-service** [comment]
Darrin,

Thank you! It has been corrected. 😊

Have a wonderful day,
Robbin

**Comment by darringraham** [comment]
If there's a better, more private way of reporting stuff like this, let me know. Don't mean to announce it to the world. :)

**Comment by sparkdevnetwork-service** [comment]
Darrin,

Thanks for asking.  For something as simple as a misspelling, you could just email me directly at info@sparkdevnetwork.org<mailto:info@sparkdevnetwork.org>.

Thanks so much,
Robbin

**Comment by darringraham** [comment]
You bet!
 
Lee said I could email him too. 
 
Thanks for all you do!
 
Darrin
