### ISSUE TITLE
GitHub Issues Widget over counts Issues

### ISSUE THREAD

**Issue by milescarmany** [SparkDevNetwork/RockWebsites#73]
### Website Issue Report

**URL:** _https://community.rockrms.com/page/1416_

**Description of Issue**

The widgets for `Classify Issues` and `Confirm Issues` show a current count of those items. When visiting each respective detail page, the count listed on that page is less. I have confirmed by manually counting on the `Classify` page, because it was short enough to do reliably.

**Comment by garrettjohnson** [comment]
Fixed. Thank you for your report!
