### ISSUE TITLE
GroupBy Lava Example Typo

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/RockWebsites#74]
### Website Issue Report

**URL:** https://community.rockrms.com/lava/filters/array-filters

The following code in the GroupBy Lava Example sets the value to groupedmembers (no caps) and then references it with groupedMembers (with a capital M). For the code to run successfully these should be consistent.

```
{% assign groupedmembers = Members | GroupBy:'GroupRole.Name' %}
<ul>
{% for group in groupedMembers %}
    {% assign parts = group | PropertyToKeyValue %}
    <li>{{ parts.Key }}</li>
    <ul>
        {% for member in parts.Value %}
            <li>{{ member.Person.FirstName }}</li>
        {% endfor %}
    </ul>
{% endfor %}
</ul>
```

**Comment by garrettjohnson** [comment]
Fixed. Thank you Brian!
