### ISSUE TITLE
Old Rocket.Chat Login Info On Profiles

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#75]
### Website Issue Report
https://community.rockrms.com/profile/MYGUID/settings/chat

**Description of Issue**

When visiting the Rock Chat menu from a user's profile on https://community.rockrms.com, there are still old instructions and (now invalid) credientials for using Rocket.Chat on stand-alone clients. There are also no instructions telling people that rockrms.com credientials are now all you need to SSO to Rocket.Chat from all clients.

**Comment by garrettjohnson** [comment]
Updated. Thank you!
