### ISSUE TITLE
Link to "Book Your Room" on RX2021 Venue Points to Page with Invalid Booking Dates

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/RockWebsites#76]
### Website Issue Report

**URL:** https://rx.rockrms.com/venue

**Description of Issue**

The "Book Your Room" link on https://rx.rockrms.com/venue is https://www.rockrms.com/rx2021hotel and currently resolves to https://www.marriott.com/event-reservations/reservation-link.mi?id=1623359728516&key=GRP&app=resvlink.

This page selects the dates of Aug 27th - Sept 4th by default.
![image](https://user-images.githubusercontent.com/605691/124153179-feaa3480-da48-11eb-9a57-de6c3c42c4f7.png)

Clicking Check Availability shows an error screen since the group block is not available on those nights.
![image](https://user-images.githubusercontent.com/605691/124153274-17b2e580-da49-11eb-9afe-5ba7d2008749.png)

Changing the dates on the initial page to the correct dates of the conference resolves the issue, but thought I would bring it to your attention in case there was a way you could change the default dates loaded. There was a quick panic at our office when they saw that the rooms were unavailable and didn't want anyone else to be confused by it. :)

**Comment by garrettjohnson** [comment]
Hi @bscottdavis thanks for letting us know! We have been working with Marriott to make sure there are rooms allocated to our block, I'll forward the issue on to them.
