### ISSUE TITLE
Search Results on Recipes Show All Content 

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#77]
### Website Issue Report

https://community.rockrms.com/recipes/search?Q=security  (this is a query I did no the keyword 'security' to demonstrate the issue)

**Description of Issue**

When searching for terms on the recipes page, the results are showing ALL of the content (description, code, everything) from within the found Recipe. This leads to some VERY long (and ugly) results you have to scroll through.

Seem like only the description and maybe 20 or so words of the content should be returned in results?

**Comment by garrettjohnson** [comment]
Fixed. Thanks!
