### ISSUE TITLE
Lava Errors in elseif Examples

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/RockWebsites#78]
### Website Issue Report

**URL:** https://community.rockrms.com/lava/tags/if-else-tags

**Description of Issue**

There's a number of errors in the elseif lava syntax, including one issue with a variable name.

![image](https://user-images.githubusercontent.com/19762670/127702231-280e7cfc-a644-438c-abe9-7b92b7edcadd.png)
![image](https://user-images.githubusercontent.com/19762670/127702238-87c83498-f986-4e3e-8c42-b9dc5a4d85b8.png)

**Comment by garrettjohnson** [comment]
Corrected. Thank you! 
![image](https://user-images.githubusercontent.com/374209/128084223-3ab1e450-6b19-4f56-a47b-d7c4089a4062.png)
