### ISSUE TITLE
"The given key was not present in the dictionary." Throughout the website

### ISSUE THREAD

**Issue by ccoleman18** [SparkDevNetwork/RockWebsites#79]
### Website Issue Report

https://community.rockrms.com/organizations/8507b438-9498-4bcc-9be5-10559adbf376

The phrase "The given key was not present in the dictionary." is throughout the website where information should be. 

When I click on my organizations and click on my church this is what the page looks like. I've seen this issue on other pages too.
![image](https://user-images.githubusercontent.com/89990537/131866993-bfbd56cd-43fa-485c-be04-06a3e53b0877.png)

**Comment by garrettjohnson** [comment]
Fixed. Thank you
