### ISSUE TITLE
Label in Organization > Packages need extra padding

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/RockWebsites#8]
### Website Issue Report

**URL:** https://community.rockrms.com/page/1346?PackageId={yourPackageId}&OrganizationId={yourOrganizationId}

**Description of Issue**
If you go to your organization and view a package, the labels in the top right need some additional padding. See the screenshot below.

![image](https://user-images.githubusercontent.com/7517351/56837571-89c38a80-6840-11e9-97e2-a4a380335ef0.png)

**Comment by garrettjohnson** [comment]
Fixed, downsized the labels and aligned them properly. Thank you!
