### ISSUE TITLE
Nov 8-19, 2021 Rock 100 Registration Instance Not Active

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/RockWebsites#80]
### Website Issue Report

**URL:** https://www.rockrms.com/rock100#upcoming-classes
**Description of Issue**

Clicking the "Register" button for the "Nov 8-19, 2021" class takes you to https://www.rockrms.com/Registration/2021Rock100Session4 which displays an error of:
 "Sorry
The selected registration could not be found or is no longer active."

**Comment by garrettjohnson** [comment]
Thank you for letting us know!
