### ISSUE TITLE
Developer Codex link incorrect on community site

### ISSUE THREAD

**Issue by MichaelAllen** [SparkDevNetwork/RockWebsites#82]
### Website Issue Report

**URL:** https://community.rockrms.com/developer

**Description of Issue**

The link for "Developer Codex" points to a file in Dropbox. However, the first page of the linked file reads:
> THIS DOCUMENT HAS MOVED TO
> https://triumph.slab.com/posts/developer-codex-orig-y3tqutbv
> PLEASE DO NOT EDIT ME HERE ANYMORE.

The link should be updated to point directly to Slab instead of the old file in Dropbox.

**Comment by nairdo** [comment]
Thanks Michael. I updated the link to redirect to the latest version of that guide.
