### ISSUE TITLE
Rock U Video "Watched" Indicators Not Working Properly

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/RockWebsites#83]
### Website Issue Report

**URL:** _[URL of the page](https://community.rockrms.com/rocku/check-in)_

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2465823/156186887-8ad27f9c-1de6-40c6-907f-e35872c8604a.png">

**Description of Issue**
Last week I watched the entire Rock U Check-In playlist back-to-back, but it's only showing that I've watched maybe a third of them. There would be times when I would be watching a video and it would just stop and endlessly buffer - which would lead me to having to reload the page to get it to begin playing again. Perhaps this is leaving a second of "unwatched" time in the middle of the video and that's causing it?

Our whole team watched these videos last week, and when I mentioned the problem to others, they also said that they experienced the video buffering issue - some at home on networks different than the one I was watching on.

**Comment by garrettjohnson** [comment]
Fixed. Thanks
