### ISSUE TITLE
Incomplete Lava Documentation (Cache Tags)

### ISSUE THREAD

**Issue by SteveSwaringen** [SparkDevNetwork/RockWebsites#85]
### Website Issue Report

**URL:** [_URL of the page_](https://community.rockrms.com/lava/commands/cache-commands)

**Description of Issue** The section on Cache Tags says, "Rock's caching engine allows for cache tags to be created, which allows for clearing several cached items at once." This suggests there is a way to clear cache items by a tag reference but if there is documentation for how to do this it is not evident. This section describes (without example) how to tag a cache item but there is no indication of how you would use those tags to clear the tagged items.

**Comment by jonedmiston** [comment]
Added a link to the documentation for cache tags.
