### ISSUE TITLE
Typo in the IsDateBetween Lava filter example code

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/RockWebsites#86]
### Website Issue Report

**URL:** https://community.rockrms.com/lava/filters/date-filters#isdatebetween

**Description of Issue**
There are a couple typos in the example code for the `IsDateBetween` filter. On the lines that assign values to `startDate` and `endDate`, there are some rogue brackets (`{{`) that snuck their way in there:
```
    {% assign startDate = {{i.FeaturedDates | Split:' to ' | First %}
    {% assign endDate = {{i.FeaturedDates | Split:' to ' | Last %}
```

**Comment by nairdo** [comment]
Thanks @JRichmond27 those typos are now fixed.
