### ISSUE TITLE
Confusion "Official Release Notes Page" sentence on rockrms.com/releasenotes

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#87]
### Website Issue Report

**URL:** _URL of the page_

https://www.rockrms.com/releasenotes

**Description of Issue**

There is a sentence at the top of each Rock release that says _You can read the details on the official [Release Notes] page._ where [Release Notes] is a link back to the page you're already on. I find this unnecessary and confusing. Does it serve an actual purpose?

![image](https://user-images.githubusercontent.com/3903408/186767460-b453814f-84c9-401f-922a-941878907647.png)

**Comment by nairdo** [comment]
Yes, that is unfortunate.  The version details and summary notes for each release (seen/used on the Rock Update block) are also being shown on that page.  We're now scrubbing that reference from the 'official' [release notes](https://www.rockrms.com/releasenotes) page.
