### ISSUE TITLE
Cannot delete people from Organization

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#88]
### Website Issue Report

https://community.rockrms.com/organizations/ee8ac32b-822b-4c54-9042-fc6505cf4ada/settings/people

(that's for my org, got there from click my Org in the community site menu, then people)

**Description of Issue**

Attempting to delete anyone from the organization results in an error message "The Group Member is assigned to a Group Member Historical"
![image](https://user-images.githubusercontent.com/3903408/191810117-8c884dcb-80be-49c0-b85a-4f8f4c1149d2.png)

**Comment by nairdo** [comment]
Thanks for reporting this Jim.  We've fixed it (via https://github.com/SparkDevNetwork/Rock-SparkSite/commit/87e1b79bc2f47abd233c6fc6e0b943dc977ac4cd) and I just deployed the fix.  I just tried it successfully so you should be able to remove members from your organization as needed.  Let me know if you are still having trouble.
