### ISSUE TITLE
Recipes 

### ISSUE THREAD

**Issue by ctkbellingham** [SparkDevNetwork/RockWebsites#89]
### Website Issue Report

**URL:** _URL of the page_ https://community.rockrms.com/recipes/297/view-email-on-webpage

**Description of Issue**
All Rock recipes are broken and displaying the following error code:
Lava Error: The relative virtual path 'https:/fat.github.io/zoom.js/js/[PAGENAME].js' is not allowed here.

Comments are still displaying, however the actual recipe will not display.
_please provide as much detail as possible_

![Screen Shot 2023-04-23 at 10 04 40 AM](https://user-images.githubusercontent.com/127696404/233853953-0bdaca3c-6d89-4c4a-acc3-f03ef41906d1.png)

**Comment by garrettjohnson** [comment]
@ctkbellingham Fixed and updated. Thank you!
