### ISSUE TITLE
Label in Organization > Packages > Version Needs Padding

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/RockWebsites#9]
### Website Issue Report

**URL:** https://community.rockrms.com/page/1347?VersionId={versionId}&PackageId={packageId}

**Description of Issue**
Extra padding needed on the label at top of page.
![image](https://user-images.githubusercontent.com/7517351/56837751-1c642980-6841-11e9-9b2c-36271f575c45.png)

**Comment by garrettjohnson** [comment]
Fixed. Thanks for the report @tscrip!
