### ISSUE TITLE
rock.rocksolidchurchdemo.com security cert has expired

### ISSUE THREAD

**Issue by SympleSynz** [SparkDevNetwork/RockWebsites#90]
### Website Issue Report

**URL:** rock.rocksolidchurchdemo.com

**Description of Issue**
The security cert for the demo site has expired and we're unable to connect via the api to the demo site for testing.

_please provide as much detail as possible_

**Comment by nairdo** [comment]
Thank you for letting us know.  Someone will be on that task shortly.

**Comment by SympleSynz** [comment]
Appears to be fixed now.  Thank you
