### ISSUE TITLE
Shortcode Manual not loading

### ISSUE THREAD

**Issue by tp-code** [SparkDevNetwork/RockWebsites#92]
### Website Issue Report

**URL:** _URL of the page_
https://community.rockrms.com/developer/book/33/121

**Description of Issue**
The Shortcode manual is not loading. Page just says "Error No book was selected"

_please provide as much detail as possible_

![Screenshot 2023-09-22 at 11 37 09 AM](https://github.com/SparkDevNetwork/RockWebsites/assets/41316251/a88b4481-fdbd-47a4-b0c6-e058a232f34f)

**Comment by jonedmiston** [comment]
Working now.
