### ISSUE TITLE
Typo on the Avatars documentation page

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/RockWebsites#93]
### Website Issue Report

**URL:** _https://community.rockrms.com/styling/components/avatars_

**Description of Issue**
_There's a typo in the 2nd line of the 4th list item of Tips section at the bottom of the page. "numnber" has an extra 'n' thrown in the middle._

![image](https://github.com/SparkDevNetwork/RockWebsites/assets/1696714/e42155c0-58af-4f9a-92cf-5095c8bcf6a7)

**Comment by jonedmiston** [comment]
Fixes
