### ISSUE TITLE
Update the valid values for the avatar Gender setting

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/RockWebsites#94]
### Website Issue Report

**URL:** _https://community.rockrms.com/styling/components/avatars_

**Description of Issue**

This is more of a request than an issue... 

I'm trying to implement GetAvatar.ashx for the first time, and I spent a while trying to figure out how to get the gender "id" number from the `person.Gender` parameter before I noticed that the `Gender` setting also accepts "Male" and "Female". 

It would be helpful if the documentation was updated to specify that the text values work as well (assuming this behavior was intended).

**Comment by jonedmiston** [comment]
@JRichmond27 even though "Male" and "Female" work, it's best that one uses 0,1 or 2. This improves the caching of the avatars.
