### ISSUE TITLE
Cannot View Community Profiles

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/RockWebsites#95]
### Website Issue Report

**URL:** _URL of the page_

https://community.rockrms.com/get-involved/community-points

**Description of Issue**

Clicking on any profile on the Community Points page results in prompt for authentication instead of showing the profile (even your own profile), when you're in fact already logged-in to the Community site. 

Following the link and authenticating (again) then takes you to the community.rockrms.com homepage instead of the profile.

![image](https://github.com/SparkDevNetwork/RockWebsites/assets/3903408/8bac6487-eee1-4583-93bc-c589bfde4c69)

**Comment by JimMichael** [comment]
Looks like this is a problem with the way links to profiles are generated on the https://community.rockrms.com/get-involved/community-points page. They are all http instead of https, which is breaking on certain browsers (in my case, Firefox on Win) and not others (Edge is fine.)

Regardless, I think all the profile links should be https these days.
![image](https://github.com/SparkDevNetwork/RockWebsites/assets/3903408/ebddb651-d703-4722-8414-03f9e2ce90ba)

**Comment by garrettjohnson** [comment]
Fixed and Updated. Thank you
