### ISSUE TITLE
All comment dates are "1 minute ago"

### ISSUE THREAD

**Issue by JRichmond27** [SparkDevNetwork/RockWebsites#97]
### Website Issue Report

**Example URL:** [https://community.rockrms.com/recipes/6/tokenize-link-shortcode](https://community.rockrms.com/recipes/6/tokenize-link-shortcode)

**Description of Issue**
The dates listed on comments throughout the community site are currently all being displayed as "1 minute ago". If you hover your mouse over the date, it does display the correct date.

![image](https://github.com/SparkDevNetwork/RockWebsites/assets/1696714/3b1af716-4288-4c34-915e-0f5b34d0bb21)

I have seen this on comments for recipes and ideas.

**Comment by jonedmiston** [comment]
This has been fixed.
