### ISSUE TITLE
Developer Codex GitBook is not public (Linked from community site)

### ISSUE THREAD

**Issue by MichaelAllen** [SparkDevNetwork/RockWebsites#98]
### Website Issue Report

**URL:** https://community.rockrms.com/developer

**Description of Issue**

The devleoper codex link from the community site goes to [this Slab document](https://triumph.slab.com/public/posts/%F0%9F%9A%A9-developer-codex-current-orig-y3tqutbv) which links to [this GitBook document](https://app.gitbook.com/o/-LZeM2HF8FOmeOnEE-hg/s/YfnQBfFoXY61g1ImoLO9/). However, the GitBook document is requesting a login.

**Comment by cabal95** [comment]
@MichaelAllen This should be fixed now! The original gitbook link you posted won't work, but if you follow the new link on the community site that one should now work.
